services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # @todo: Get rid of all aliases:
    #        a) use direct alias injection instead of autowiring,
    #        b) move those aliases to bundles they come from.
    #
    # Why using these is bad for you? When working on external bundle you can easily fall into trap
    # that these are available but guess not... these are not. You can use autowiring for these services
    # only because you have EzPlatformAdminUiBundle enabled.
    #

    # Kernel
    eZ\Publish\API\Repository\Repository: '@ezpublish.api.repository'
    eZ\Publish\API\Repository\ContentService: '@ezpublish.api.service.content'
    eZ\Publish\API\Repository\ContentTypeService: '@ezpublish.api.service.content_type'
    eZ\Publish\API\Repository\LanguageService: '@ezpublish.api.service.language'
    eZ\Publish\API\Repository\LocationService: '@ezpublish.api.service.location'
    eZ\Publish\API\Repository\ObjectStateService: '@ezpublish.api.service.object_state'
    eZ\Publish\API\Repository\RoleService: '@ezpublish.api.service.role'
    eZ\Publish\API\Repository\SearchService: '@ezpublish.api.service.search'
    eZ\Publish\API\Repository\SectionService: '@ezpublish.api.service.section'
    eZ\Publish\API\Repository\UserService: '@ezpublish.api.service.user'
    eZ\Publish\API\Repository\URLService: '@ezpublish.api.service.url'
    eZ\Publish\API\Repository\URLAliasService: '@ezpublish.api.service.url_alias'
    eZ\Publish\API\Repository\TrashService: '@ezpublish.api.service.trash'
    eZ\Publish\API\Repository\BookmarkService: '@ezpublish.api.service.bookmark'

    eZ\Publish\API\Repository\PermissionResolver:
        factory: 'eZ\Publish\API\Repository\Repository:getPermissionResolver'

    eZ\Publish\Core\Helper\FieldsGroups\FieldsGroupsList: '@ezpublish.fields_groups.list'
    eZ\Publish\Core\MVC\ConfigResolverInterface: '@ezpublish.config.resolver'

    eZ\Publish\Core\MVC\Symfony\SiteAccess: '@ezpublish.siteaccess'

    # Repository Forms
    EzSystems\RepositoryForms\Form\Type\Role\LimitationType: '@ezrepoforms.policy.limitation.form'
    EzSystems\RepositoryForms\EventListener\ViewTemplatesListener: '@ezrepoforms.view_templates_listener'
    EzSystems\RepositoryForms\Form\ActionDispatcher\ContentDispatcher: '@ezrepoforms.action_dispatcher.content'

    # Support Tools
    EzSystems\EzSupportToolsBundle\SystemInfo\SystemInfoCollectorRegistry: '@support_tools.system_info.collector_registry'

    # Symfony
    Symfony\Component\Translation\TranslatorInterface: '@translator'

